### ISSUE TITLE
Where are SDLJingle strings intended to be used?

### ISSUE THREAD

**Issue by joeljfischer** [smartdevicelink/SmartDeviceLink-iOS#78]
`SDLTTSChunkFactory.h` is the only file that imports the file, but it doesn't use the class in any way (which is also an issue). Are `SDLJingle` strings supposed to be passed into the string `text` parameter for `SDLTTSChunkFactory` methods?

**Comment by mikeburke106** [comment]
Yes, the "jingles" are supposed to be passed in as text when SpeechCapabilities type is `PRE_RECORDED`.  Another thing to note is that when SpeechCapabilities type is `SILENCE`, the text field should be populated with a number representing how many milliseconds of silence the TTSChunk represents.

I don't think either of these cases are well-documented anywhere... and, obviously, since we can't [sanitize user inputs](https://github.com/smartdevicelink/sdl_android/issues/10), there is no way for the mobile libraries to check these values, resulting in a rejected message with result code `INVALID_DATA`.

Ideally, we should define a factory method that takes in the SDLJingle enum and automatically assume the type as `PRE_RECORDED` and a similar method taking in an int value for `SILENCE`.  Developers could still mess it up via the setter methods, but it at least makes it a bit easier to comprehend in code (and gives you a reason to import that header file).
